#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

application=RichardsFoam3

runApplication blockMesh

runApplication $application

runApplication -s postProcess \
    $application -postProcess -time 1000000:

#------------------------------------------------------------------------------
